package com.example.model

import androidx.compose.ui.graphics.Color

/**
 * 10 distinct thematic worlds covering 100 levels (10 levels per world).
 * Each theme defines board visuals, wall styles, floor aesthetics, friction, and atmosphere.
 */
enum class WorldTheme(
    val id: Int,
    val title: String,
    val subtitle: String,
    val levelRange: IntRange,
    val boardBackground: Color,
    val boardBorder: Color,
    val wallColor: Color,
    val wallBevelColor: Color,
    val wallShadowColor: Color,
    val floorLineColor: Color,
    val floorAccentColor: Color,
    val holeColor: Color,
    val holeRimColor: Color,
    val goalColor: Color,
    val goalGlowColor: Color,
    val ballTint: Color,
    val rollingFriction: Float, // Higher = more slippery/less drag
    val bounceRestitution: Float,
    val description: String
) {
    CLASSIC_TEAK(
        id = 1,
        title = "Vintage Teak",
        subtitle = "Classic Brass Labyrinth",
        levelRange = 1..10,
        boardBackground = Color(0xFF2A1810),
        boardBorder = Color(0xFF5C3317),
        wallColor = Color(0xFFB8860B),
        wallBevelColor = Color(0xFFF5DEB3),
        wallShadowColor = Color(0x66000000),
        floorLineColor = Color(0x22FFFFFF),
        floorAccentColor = Color(0x15D2B48C),
        holeColor = Color(0xFF0F0805),
        holeRimColor = Color(0xFF8B4513),
        goalColor = Color(0xFF10B981),
        goalGlowColor = Color(0x8834D399),
        ballTint = Color(0xFFE2E8F0),
        rollingFriction = 0.982f,
        bounceRestitution = 0.35f,
        description = "Polished mahogany wood with gleaming brass pins and smooth tactile rolling."
    ),
    CYBER_NEON(
        id = 2,
        title = "Cyber Matrix",
        subtitle = "Neon Grid Corridor",
        levelRange = 11..20,
        boardBackground = Color(0xFF090D1A),
        boardBorder = Color(0xFF1E1B4B),
        wallColor = Color(0xFF06B6D4),
        wallBevelColor = Color(0xFF67E8F9),
        wallShadowColor = Color(0x8800F5FF),
        floorLineColor = Color(0x2506B6D4),
        floorAccentColor = Color(0x20EC4899),
        holeColor = Color(0xFF030712),
        holeRimColor = Color(0xFFEC4899),
        goalColor = Color(0xFF3B82F6),
        goalGlowColor = Color(0x9960A5FA),
        ballTint = Color(0xFFE0F2FE),
        rollingFriction = 0.985f,
        bounceRestitution = 0.38f,
        description = "Pulsing neon rails and cybernetic circuits with electronic speed."
    ),
    ANCIENT_TEMPLE(
        id = 3,
        title = "Sun Temple",
        subtitle = "Aztec Sandstone Relic",
        levelRange = 21..30,
        boardBackground = Color(0xFF2B1D12),
        boardBorder = Color(0xFF78350F),
        wallColor = Color(0xFFD97706),
        wallBevelColor = Color(0xFFFDE68A),
        wallShadowColor = Color(0x66000000),
        floorLineColor = Color(0x20F59E0B),
        floorAccentColor = Color(0x15D97706),
        holeColor = Color(0xFF180F08),
        holeRimColor = Color(0xFFB45309),
        goalColor = Color(0xFFF59E0B),
        goalGlowColor = Color(0x88FCD34D),
        ballTint = Color(0xFFFEF3C7),
        rollingFriction = 0.978f,
        bounceRestitution = 0.30f,
        description = "Carved desert sandstone with gold sun rune inlays and crumble traps."
    ),
    DEEP_SPACE(
        id = 4,
        title = "Cosmic Void",
        subtitle = "Starlight Quantum Realm",
        levelRange = 31..40,
        boardBackground = Color(0xFF070519),
        boardBorder = Color(0xFF2E1065),
        wallColor = Color(0xFF8B5CF6),
        wallBevelColor = Color(0xFFDDD6FE),
        wallShadowColor = Color(0x778B5CF6),
        floorLineColor = Color(0x25A78BFA),
        floorAccentColor = Color(0x15C084FC),
        holeColor = Color(0xFF02010A),
        holeRimColor = Color(0xFF6D28D9),
        goalColor = Color(0xFFA855F7),
        goalGlowColor = Color(0x99C084FC),
        ballTint = Color(0xFFF3E8FF),
        rollingFriction = 0.990f,
        bounceRestitution = 0.42f,
        description = "Cosmic nebula with zero-g stardust and strong vortex gravitational wells."
    ),
    STEAMPUNK_FOUNDRY(
        id = 5,
        title = "Iron Foundry",
        subtitle = "Industrial Copper Works",
        levelRange = 41..50,
        boardBackground = Color(0xFF1C140E),
        boardBorder = Color(0xFF431407),
        wallColor = Color(0xFFEA580C),
        wallBevelColor = Color(0xFFFED7AA),
        wallShadowColor = Color(0x66000000),
        floorLineColor = Color(0x20F97316),
        floorAccentColor = Color(0x18EA580C),
        holeColor = Color(0xFF0C0704),
        holeRimColor = Color(0xFFC2410C),
        goalColor = Color(0xFFF97316),
        goalGlowColor = Color(0x88FB923C),
        ballTint = Color(0xFFFFEDD5),
        rollingFriction = 0.976f,
        bounceRestitution = 0.32f,
        description = "Riveted boiler plates, glowing furnace grates, and heavy bronze inertia."
    ),
    GLACIAL_ICE(
        id = 6,
        title = "Glacial Cavern",
        subtitle = "Subzero Frost Abyss",
        levelRange = 51..60,
        boardBackground = Color(0xFF081C2E),
        boardBorder = Color(0xFF075985),
        wallColor = Color(0xFF38BDF8),
        wallBevelColor = Color(0xFFE0F2FE),
        wallShadowColor = Color(0x6638BDF8),
        floorLineColor = Color(0x257DD3FC),
        floorAccentColor = Color(0x20BAE6FD),
        holeColor = Color(0xFF030E18),
        holeRimColor = Color(0xFF0284C7),
        goalColor = Color(0xFF06B6D4),
        goalGlowColor = Color(0x8867E8F9),
        ballTint = Color(0xFFF0F9FF),
        rollingFriction = 0.994f, // Very slippery!
        bounceRestitution = 0.36f,
        description = "Ultra-low friction frozen glacier ice requiring feather-light tilt control."
    ),
    VOLCANIC_CORE(
        id = 7,
        title = "Magma Core",
        subtitle = "Molten Obsidian Trench",
        levelRange = 61..70,
        boardBackground = Color(0xFF1A0808),
        boardBorder = Color(0xFF7F1D1D),
        wallColor = Color(0xFFDC2626),
        wallBevelColor = Color(0xFFFECACA),
        wallShadowColor = Color(0x88EF4444),
        floorLineColor = Color(0x25F87171),
        floorAccentColor = Color(0x20DC2626),
        holeColor = Color(0xFF0D0202),
        holeRimColor = Color(0xFFB91C1C),
        goalColor = Color(0xFFEF4444),
        goalGlowColor = Color(0x99F87171),
        ballTint = Color(0xFFFFE4E6),
        rollingFriction = 0.972f,
        bounceRestitution = 0.28f,
        description = "Black obsidian slabs suspended over fiery cracks and molten hazards."
    ),
    ZEN_GARDEN(
        id = 8,
        title = "Zen Sanctuary",
        subtitle = "Bamboo & River Sand",
        levelRange = 71..80,
        boardBackground = Color(0xFF142018),
        boardBorder = Color(0xFF064E3B),
        wallColor = Color(0xFF059669),
        wallBevelColor = Color(0xFFA7F3D0),
        wallShadowColor = Color(0x66000000),
        floorLineColor = Color(0x2034D399),
        floorAccentColor = Color(0x1810B981),
        holeColor = Color(0xFF07120C),
        holeRimColor = Color(0xFF047857),
        goalColor = Color(0xFF10B981),
        goalGlowColor = Color(0x886EE7B7),
        ballTint = Color(0xFFECFDF5),
        rollingFriction = 0.965f, // Tactical sand resistance
        bounceRestitution = 0.30f,
        description = "Raked gravel ripples, emerald bamboo boundaries, and calming balance."
    ),
    CYBER_BIOSPHERE(
        id = 9,
        title = "Emerald Bio",
        subtitle = "Toxic Cyber Flora",
        levelRange = 81..90,
        boardBackground = Color(0xFF0A1F0D),
        boardBorder = Color(0xFF14532D),
        wallColor = Color(0xFF16A34A),
        wallBevelColor = Color(0xFFBBF7D0),
        wallShadowColor = Color(0x7722C55E),
        floorLineColor = Color(0x254ADE80),
        floorAccentColor = Color(0x2022C55E),
        holeColor = Color(0xFF041206),
        holeRimColor = Color(0xFF15803D),
        goalColor = Color(0xFF22C55E),
        goalGlowColor = Color(0x9986EFAC),
        ballTint = Color(0xFFF0FDF4),
        rollingFriction = 0.978f,
        bounceRestitution = 0.38f,
        description = "Luminescent bio-plasma conduits and repulsive magnetic spore nodes."
    ),
    CELESTIAL_OLYMPUS(
        id = 10,
        title = "Divine Aether",
        subtitle = "Golden Marble Ascendance",
        levelRange = 91..100,
        boardBackground = Color(0xFF1A1A2E),
        boardBorder = Color(0xFF7851A9),
        wallColor = Color(0xFFF59E0B),
        wallBevelColor = Color(0xFFFFFBEB),
        wallShadowColor = Color(0x77F59E0B),
        floorLineColor = Color(0x30FDE68A),
        floorAccentColor = Color(0x25F59E0B),
        holeColor = Color(0xFF0C0A1A),
        holeRimColor = Color(0xFFD97706),
        goalColor = Color(0xFFFBBF24),
        goalGlowColor = Color(0xAAFEF08A),
        ballTint = Color(0xFFFFFFFF),
        rollingFriction = 0.985f,
        bounceRestitution = 0.40f,
        description = "Pristine celestial marble inlaid with pure gold leaf. The ultimate master trials."
    );

    companion object {
        fun forLevel(level: Int): WorldTheme {
            val clamped = level.coerceIn(1, 100)
            return entries.firstOrNull { clamped in it.levelRange } ?: CLASSIC_TEAK
        }
    }
}
